language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode10.3
    compiler: clang
addons:
  homebrew:
    packages:
    - qt5
script:
- export Qt5_DIR=/usr/local/opt/qt5/lib/cmake
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX="../dataflow++-$TRAVIS_TAG" -G"Xcode" ..
- cmake --build . --config Release
- ctest -V -C Release .
- cmake --build . --config Debug
- ctest -V -C Debug .
