name: CMake

on: [push]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -GXcode

    - name: Build Debug
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Debug

    - name: Test Debug
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -V -C Debug

    - name: Build Release
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test Release
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -V -C Release
